{% set name = "pyscript-cli" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyscript_cli-{{ version }}.tar.gz
  sha256: 301dabcfb7040d51426014e4e80e27d3f8dbd4e27b1f627ebde802d88048620e

build:
  skip: true  # [py<39]
  entry_points:
    - pyscript = pyscript.cli:app
  script: |
    set PYTHONIOENCODING=utf-8
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - importlib-metadata  # [py<38]
    - jinja2 <3.2
    - pluggy ==1.5.0
    - rich <=13.7.1
    - toml <0.11
    - typer <=0.9.0
    - platformdirs <4.3
    - requests <=2.31.0

test:
  imports:
    - pyscript
  commands:
    - pip check
    - pyscript --help
  requires:
    - pip

about:
  home: https://github.com/pyscript/pyscript-cli
  summary: Command Line Interface for PyScript
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
    - madhur-tandon
