{% set name = "pyscript-cli" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 301dabcfb7040d51426014e4e80e27d3f8dbd4e27b1f627ebde802d88048620e

build:
  entry_points:
    - pyscript = pyscript.cli:app
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9
  run:
    - jinja2 <3.2
    - platformdirs <4.3
    - pluggy ==1.5.0
    - python >=3.9
    - requests <=2.31.0
    - rich <=13.7.1
    - toml <0.11
    - typer <=0.9.0

test:
  imports:
    - pyscript
  commands:
    - pip check
    - pyscript --help
  requires:
    - pip

about:
  home: https://github.com/pyscript/pyscript-cli
  summary: Command Line Interface for PyScript
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
